### ISSUE TITLE
Cannot extract a file from path

### ISSUE THREAD

**Issue by stepesdrabes** [rbcprolabs/icon_font_generator#19]
I'm facing this issue when I'm trying to generate the icons.

`C:\Users\theza\AndroidStudioProjects\reactions_test>icon_font_generator --from=assets/ic
ons --class-name=UiIcons --out-font=assets/fonts/io_icons.ttf --out-flutter=lib/widgets/
icons.dart
Unhandled exception:
Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2636:7)
#1      new File.fromUri (dart:io/file.dart:248:49)
#2      GenerateCommand.run (file:///C:/Users/theza/AppData/Local/Pub/Cache/hosted/pub.d
artlang.org/icon_font_generator-3.1.0/bin/icon_font_generator.dart:111:27)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#4      main (file:///C:/Users/theza/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ico
n_font_generator-3.1.0/bin/icon_font_generator.dart:13:5)
<asynchronous suspension>
Unhandled exception:
Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2636:7)
#1      new File.fromUri (dart:io/file.dart:248:49)
#2      GenerateCommand.run (file:///C:/Users/theza/AppData/Local/Pub/Cache/hosted/pub.d
artlang.org/icon_font_generator-3.1.0/bin/icon_font_generator.dart:111:27)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#4      main (file:///C:/Users/theza/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ico
n_font_generator-3.1.0/bin/icon_font_generator.dart:13:5)
<asynchronous suspension>`

**Comment by Jordan1122** [comment]
Same here, can somebody help, please?

**Comment by Yahhi** [comment]
The same error. Would appreciate any help

**Comment by urusai88** [comment]
I think 
https://github.com/rbcprolabs/icon_font_generator/blob/76d8e8e96114c9b40c7b8e031516a1dea6855484/bin/icon_font_generator.dart#L111-L113
should be like
```dart
final iconsMap = File.fromUri(tempOutDirectory.uri.resolve(
    path.basenameWithoutExtension(argResults!['out-font']) + '.json'));
```

**Comment by christiankadjo** [comment]
Hello, i have the same problem...No fix yet ?

**Comment by JKazimiers** [comment]
Hi, is there any update yet?
I still have the same problem.
